version: '3.2'

services:
  php:
    build: ./
    container_name: laravel_container
    depends_on: [db]
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html/

  db:
    build: ./database
    container_name: db_container
    ports:
      - "3306:3306"
    volumes:
      - ./database/data/:/var/lib/mysql
